### PR TITLE
Add a MasterMultiSelectWidget

### PR DESCRIPTION
**Pull request by sdelcourt**
Hi ,

I added a MasterMultiSelectWidget based on the work done for MasterSelectWidget.
I also added robot tests based on the MasterSelectDemo content type to prove my refactorings didnt break any behaviour of the original product.

It would be awesome if this could be reviewed, merged and released.

Regards,

Simon

### CODE REVIEW

**Comment by sdelcourt** [comment]
Hi @frisi

Since your seem the last active contributor, could you please review my pull request?

Regards,

**Comment by jensens** [comment]
Good work! Imo we can merge it, but i would like to have a second opinion.

**Comment by ebrehault** [comment]
The feature is nice and the code looks good.
+1 for merging.

**Comment by sdelcourt** [comment]
@jensens, @ebrehault . Thank you for taking the time to review this.

**Pull request merged**
